### PR TITLE
fix: 🐛  resolve binaries from current package location and memoize costly operations

### PR DESCRIPTION
**Pull request by remorses**
The commands using `-r` were failing in yarn berry workspaces because the binaries were resolved from `process.cwd()`, now they are resolved from the current package location instead

The commands with `-r` were also very slow because some costly operation like `getInstallState`  were executed for every package, now they are memoized

After the changes below everything works as expected 😀

### CODE REVIEW

**Comment by remorses** [comment]
Hey @folke, can you take a look?

**Comment by folke** [comment]
Thank you for working on this!

I merged this about an hour ago, but hadn't checked first 😬.

The changes currently give a TS error on the import of the pnpapi.

Haven't really looked too much into it, but I assume you only want the types?

If so, just change it to an `import type` instead.

If that is the part that imports a package's pnpapi.js file, then you should either use a dynamic import with proper filename (is async) or use require.

Otherwise, this might possibly break using ultra in packages not using yarn.

Would be great if you could look into this and create a new PR from the current main branch (your previous changes or on that already).

You can do ultra build to see if everything is OK.

Also, just ignore the lint errors for reduce. I already fixed that on my laptop, but didn't push it yet. On mobile right now.

Thanks again!

**Comment by remorses** [comment]
I import the pnpapi  just for the type, I also installed ‘@types/o papi’ so typescript should be ok, I think the problem is just the linter, maybe using import type will remove it, I will try tomorrow

**Comment by folke** [comment]
Thank you for the info! Had a look at the code and fixed the linting errors. Will push a new release in a bit.

**Pull request merged**
