### PR TITLE
fix(git): 🐛 .gitignore considered in getGitFiles

### LINKED ISSUE #117: expect can setting exclude some file in .ultra.cache.json
First, `ultra-runner` is awesome!!!
 
But, there is a using case: 

some build process can async produce files or expect exclude .gitignore don't put in .ultra.cache.json

``` 
async getFiles(directory: string, exclude: string[] = []): Promise<GitFiles> {
    ...
}

async function getPackageFiles(
  root: string,
  workspace: Workspace | undefined
): Promise<PackageFiles> {
  return {
    files: await cache.getFiles(root),
    deps: getDependencies(root, workspace),
  }
}
```

### PR DESCRIPTION
**Pull request by lxgreen**
this PR fixes #117 by excluding patterns in .gitignore (if exists)

### CODE REVIEW

**Comment by wesselvdv** [comment]
I don't think using the .gitignore is a good idea. This will definitely break the promise of ultra-runner working without configuration. Most build artifacts are excluded by default in a .gitignore, rendering it completely useless for this purpose.

With that said, I do think it would be a good idea to have a `.ultraignore` kind of file. (fight me on the nomenclature) This ignore file would allow a granular control of what we consider a change that requires a rebuild. In the case of ignoring node_modules for example, because if one uses exact version targets in package.json, then the package.json would change and one doesn't have to consider node_modules anymore.

**Comment by lxgreen** [comment]
> Most build artifacts are excluded by default in a .gitignore, rendering it completely useless for this purpose

I think I don't understand something in ultra-runner then. I thought the idea is to track changes in source code, and rebuild only a required portion of monorepo when the code is changed. 
What's the point to track the build artifacts? I see, currently ultra-runner caches all the `node_modules` and `dist` directories in `.ultra.cache.json`. 
I'd appreciate it if you could explain this amazing project ideology, thanks in advance!

**Comment by wesselvdv** [comment]
I have to be honest and say that clarity I had when typing my response is no longer there. I believe I had some good arguments as to why it’s useless yet I failed to memorize them. The only one that comes to mind is that it needs it when determining the dependencies have changed?

**Comment by lxgreen** [comment]
hmm, I see.. kinda if you track the build artifacts, you exactly know when the build run last time. it can be useful to detect changes in source code that require rebuild. i initially thought that git status alone is enough, but i didn't consider the local build state. so, it makes sense not to exclude the .gitignore patterns, and the .ultraignore approach is really helpful in my case. i'll update the PR.
Another question -- when i change a single source file in my monorepo, `ultra --build` builds the whole monorepo rather the specific repo the change file resides in (as i expected). The project is yarn workspaces based monorepo, and it has a single `node_modules` in the root. Does this happen due to this setup? Does ultra-runner capable to apply a build filter automatically, according to the change scope?

**Comment by wesselvdv** [comment]
> Another question -- when i change a single source file in my monorepo, `ultra --build` builds the whole monorepo rather the specific repo the changed file resides in (as i expected). The project is yarn workspaces based monorepo, and it has a single `node_modules` in the root. Does this happen due to this setup?

Depends on how you're managed your packages inside your monorepo. If you're correctly indicating the dependencies between packages in your package.json then ultra will be able to detect that a change in a package that's required by all your other packages in you repo, will need a full rebuild.

> Does ultra-runner capable to apply a build filter automatically, according to the change scope?

Yes, see commment above. If you've declared your dependencies between your packages correctly then it should work ootb. This is one of the reasons why I use ultra, because of how nicely this works.

**Comment by lxgreen** [comment]
#168

**Comment by folke** [comment]
The reason we track changes inside node_modules for example is to trigger a new build when one of the dependencies change. (although that probably also change package.json to some extend).

Another reason is if you make changes to build artifacts outside of `ultra`.

Tracking all files ensures your builds will always be fresh.

I do like the proposal to have an `.ultraignore`, so feel free to update this PR. 

Thanks!

**Comment by folke** [comment]
You already added a second PR. thanks :)

**Comment by folke** [comment]
@lxgreen @wesselvdv just remembered the main reason I added artifacts to check for a rebuild.

It was mostly for monorepos, where you have other packages in your monorepo linked inside node_modules. Without checking for those files, a new build would not be triggered if one of your internal dependencies had chaned.

**Comment by alexkrautmann** [comment]
Coincidently, I just ran into this issue myself and found the PR was merged with a fix. In my case, type-checking from my monorepo root causes package-level `*.tsbuildinfo` files to change which triggers a rebuild in ultra.

@folke Are you planning to publish a version with the fix anytime soon?

Thanks for the work you all have done on this package, It's been working great for me so far.

**Comment by folke** [comment]
@alexkrautmann just made a new release 🚀

**Pull request closed without merging**
